### ISSUE TITLE
TestMain  配置信息获取不合理

### ISSUE THREAD

**Issue by wuqinqiang** [yedf/dtm#102]
TestMain 方法中先从配置文件读取数据库配置，不管存不存在环境变量最终都会被代码中写死的值覆盖，这样本地运行测试用例还得手动改代码。这块可以改成如果有环境变量，从环境变量中取配置值。

**Comment by yedf2** [comment]
能否说一下更具体的场景，没太明白

**Comment by wuqinqiang** [comment]
我的意思是当我在本地执行 go test ./...的时候，
![Xnip2021-12-20_10-48-56](https://user-images.githubusercontent.com/36129334/146705011-116ca99c-265c-447c-8062-ec79180e2301.jpg)

**Comment by yedf2** [comment]
如果你是在做dtm的开发，那么你应当使用默认的dtm仓库里的conf.sample.yml，不存在需要兼容其他配置的情况

TestMain里面的这部分代码，是根据你的环境变量设置，选择一个合适的存储引擎进行测试。默认选择redis是因为他的性能最高，能够最快速跑完单侧。然后在CI中，所有的存储引擎都会被测试，保证覆盖率。

TestMain的代码，不会在dtm的代码中运行，所以是没问题的
