### ISSUE TITLE
一些问题咨询

### ISSUE THREAD

**Issue by busyfree** [yedf/dtm#11]
具体业务开发要在dtm框架里面实现？

dtm 里 orm 相关代码可能无法做到db上的分布式，db层分布式怎么实现？上 db proxy 实现？

**Comment by yedf2** [comment]
您能否把您的业务场景，更具体的描述出来？例如你的db上的分布式是指什么？

**Comment by busyfree** [comment]
如涉及到在 分库，分表上实现事务。

**Comment by yedf2** [comment]
您好，按照微服务的设计原则，大多数情况下一个微服务通常访问一个数据库，一个微服务有一个本地事务。dtm会将多个微服务的本地事务组合成一个分布式事务，保证正确性

对于分库的情况，您只要保证了上述原则，那么就可以采用dtm

如果您的分库是在db proxy层实现，那么需要相关的db proxy对您微服务上的本地事务有支持。

**Comment by busyfree** [comment]
了解，感谢解答。
