### ISSUE TITLE
没有user_account表

### ISSUE THREAD

**Issue by baiyuxiong** [yedf/dtm#14]
安装好后，执行：
go run app/main.go quick_start
提示：
----panic unknown response: {"code":500,"message":"Error 1146: Table 'dtm_busi.user_account' doesn't exist"}, will be retried handlered

看数据库里，只有三张表：
![image](https://user-images.githubusercontent.com/230689/128617069-0ad3d8f1-65db-47ca-95a6-d8595c1e15b7.png)

**Comment by baiyuxiong** [comment]
![image](https://user-images.githubusercontent.com/230689/128617136-c9234e73-14ef-402f-9fe3-09ee02390241.png)

**Comment by yedf2** [comment]
@baiyuxiong 已调整
