### ISSUE TITLE
新手提问,让一个变量等于一个方法的作用是什么

### ISSUE THREAD

**Issue by MasterJoyHunan** [yedf/dtm#20]
比如在 dtmsvr/utils.go 文件中
var p2e = dtmcli.P2E
p2e 作用是什么? 是编译的时候会优化吗?

**Comment by yedf2** [comment]
没有特别作用，就是以后只用写简短的p2e就行了，每次敲dtmcli.P2E，字符较多

**Comment by MasterJoyHunan** [comment]
好的,谢谢解答
