### ISSUE TITLE
docker build失败，能否把基础镜像推到dockerhub？

### ISSUE THREAD

**Issue by hitzhangjie** [yedf/dtm#23]

**Comment by hitzhangjie** [comment]
是我的代理配置的问题，忽略

**Comment by hitzhangjie** [comment]
FROM基础镜像这个拉不下来，体验阶段不是很好，建议放到更通用的dockerhub上

**Comment by hitzhangjie** [comment]
直接app目录下go build也可以在本地快速体验

**Comment by yedf2** [comment]
没太明白你期望的是什么样？在国内daocloud.io比dockerhub快。
如果你有更好的建议，可以提个PR @hitzhangjie
