### ISSUE TITLE
python可以接入grpc服务吗？

### ISSUE THREAD

**Issue by hyufeng** [yedf/dtm#26]
我看到python的客户端是http服务，请问可以接入grpc服务吗？

**Comment by yedf2** [comment]
当然可以。我对这块不够熟悉，因此暂时没有提供。如果您近期确定会接入，我可以现学现写提供帮助

**Comment by hyufeng** [comment]
感谢，提供帮助更好，我就是确认一下是否支持，支持的话自己就动手啦

**Comment by yedf2** [comment]
@hyufeng 如果您实现了python-grpc的版本，希望到时候告诉我，我把它放到这个组织里面来，review后作为dtm的官方版本
