### ISSUE TITLE
msyql8.0的情况下运行测试用例创建表出现Specified key was too long; max key length is 1000 bytes

### ISSUE THREAD

**Issue by zhenhua1** [yedf/dtm#31]
![726a01b8370ddbcb27b0396460bf971](https://user-images.githubusercontent.com/22211474/134611440-a8f17ba7-b3d3-48ea-8858-bf99becaea1d.png)

**Comment by yedf2** [comment]
我初步试了一下，将compose.mysql.yml改成mysql8，暂未复现你说的这个问题
