### ISSUE TITLE
请问下这里的BarrierID是做什么用的呢？

### ISSUE THREAD

**Issue by lanlanlanlanlanchengzhu** [yedf/dtm#35]
![image](https://user-images.githubusercontent.com/31987529/134771171-658bd572-29a9-4370-9e22-523847ad0a40.png)

**Comment by yedf2** [comment]
dtm可以支持一个服务访问多个数据源，只需要吧每个数据源的访问放在一个barrier.Call里面即可

这个barrierId就是为了给每个Call分配一个新的id，避免唯一键冲突

**Comment by cometwk** [comment]
这里 originAffected 的 insert 语句， 这样处理，更合适???

```go
if ti.BranchType == BranchCancel || ti.BranchType == BranchCompensate {
  // 放在这里,  更合适???
  originAffected, _ := insertBarrier(tx, ti.TransType, ti.Gid, ti.BranchID, originType, bid, ti.BranchType)
  if  originAffected > 0 {
    return
  }
}
```

**Comment by yedf2** [comment]
区别不大，为了更简单的讲解子事务屏障，更短些的代码，现有的做法比较好
