### ISSUE TITLE
SAGA模式支持sql解析吗

### ISSUE THREAD

**Issue by zhangxiaoyus** [yedf/dtm#36]
我看到python的示例里面的SAGA模式回退是使用的手动写的补偿函数，该项目支持像SAGA那种sql解析逆向回退吗

**Comment by yedf2** [comment]
您好，无论是seata还是其他的分布式事务框架，SAGA模式的回退都是手动写的补偿函数

seata里面的AT模式是采用sql解析回退，这种实现有潜在的脏回滚问题。他的原理是解析SQL，把修改前的数据保存起来，当回滚时，将原先的数据再写入。在性能方面，当前的AT模式比XA好一些，但是在修改后回滚前，数据又被其他人修改，就会导致脏回滚，有数据一致性上的问题。

**Comment by zhangxiaoyus** [comment]
我明白了，谢谢
