### ISSUE TITLE
http 的响应常量是不是定义错了？

### ISSUE THREAD

**Issue by caiziqi33** [yedf/dtm#60]
var MapSuccess = dtmimp.MapSuccess

// MapFailure HTTP result of FAILURE
var MapFailure = dtmimp.MapFailure

？？？？

**Comment by yedf2** [comment]
这里的MapSuccess和MapFailure会在examples里面作为返回值，最后被Marshal成一个Json，返回给调用者
您说的错了，是指？

**Comment by caiziqi33** [comment]
不好意思，上面截图是我本地改了，源码里面MapFailure对应的值是：dtmimp.MapSuccess
![image](https://user-images.githubusercontent.com/35523103/142788705-bc957f55-e33c-4167-99c8-8feb6e02e6bb.png)

**Comment by yedf2** [comment]
明白了，帮忙提个PR？非常感谢
