### ISSUE TITLE
SAGA不支持编排型吗，不依赖控制器的那种

### ISSUE THREAD

**Issue by li5ch** [yedf/dtm#69]

**Comment by yedf2** [comment]
这个问题已经加微信沟通。

以事件消息方式驱动的方式，来做数据一致性，最早源自亚马逊的架构师的一片论文。详细可以参考: https://segmentfault.com/a/1190000040321750

而SAGA源自另一篇论文，也在前面链接的文章中找到

将事件驱动的这种方式，结合作者提出的另一个事件溯源，作者称之为协作性SAGA。实质上，这种方式和SAGA，并没有紧密管理。但因为是Chris Richardson提出的，他的影响力很大，所以许多文章都引用了他的说法。

目前来看市面上的各个分布式事务框架，都没有采用事件驱动加溯源的方式，也暂未有用户提出这方面的需求，因此dtm并没有计划做这方面的实现。

**Comment by li5ch** [comment]
好的，谢谢
