### ISSUE TITLE
版本发布疑问？

### ISSUE THREAD

**Issue by zurmokeeper** [yedf/dtm#75]
请问新版本的发布有什么规则吗？感觉有点随意呢，v1.5.x和v1.6.x发布的间隔怎么短，而且更新的内容也不多，也不是那种重大的功能和bug修改，给人一个不是很稳定，还在快速迭代但是每次的更新内容又很少的错觉。虽然官方在v1.0有说明已经很稳定了，但是给人的信心不够。

**Comment by yedf2** [comment]
v1.5.x和v1.6.x之间的间隔并不短哈，二十多天

第二位版本升级，通常是大的功能发布，第三位版本升级，通常是bug或者小功能上线。

v1.6增加了go-zero支持，随后又增加了polaris支持，这两个微服务框架的支持，是大功能，只是在dtm里面的代码修改量不大，主要代码都在grpc的resolver了。

增加了Polaris支持后，用户案例中增加了腾讯，希望这样重量级的用户，能给给你带来更大的信心！

**Comment by zurmokeeper** [comment]
> v1.5.x和v1.6.x之间的间隔并不短哈，二十多天
> 
> 第二位版本升级，通常是大的功能发布，第三位版本升级，通常是bug或者小功能上线。
> 
> v1.6增加了go-zero支持，随后又增加了polaris支持，这两个微服务框架的支持，是大功能，只是在dtm里面的代码修改量不大，主要代码都在grpc的resolver了。
> 
> 增加了Polaris支持后，用户案例中增加了腾讯，希望这样重量级的用户，能给给你带来更大的信心！

我指的是1.6.0-1.6.3这几个,虽然第三位版本升级，通常是bug或者小功能上线，但是一天一个版本，感觉必要性不是很高，一个星期的小版本也很好。

**Comment by yedf2** [comment]
目前dtm还处于快速迭代变化当中，有发现bug或者新功能，就快速发版打包，方便最新的用户获取到最新的内容。目前还没有按照固定的节奏去发版
