### ISSUE TITLE
[GRPC]服务端设置返回结构数据，DTM回调报错

### ISSUE THREAD

**Issue by yimuczhou** [yedf/dtm#84]
![image](https://user-images.githubusercontent.com/4995476/146315379-fa769a46-0e4f-4ac9-a2d5-bc8fe143638f.png)
![image](https://user-images.githubusercontent.com/4995476/146315384-52537eeb-abe2-4435-92dc-8548dfa65434.png)

如果将CommonRes里面的Code和Message去掉DTM回调就正常处理
![image](https://user-images.githubusercontent.com/4995476/146315468-11f57dd1-5a61-40b8-9695-ee5143bb2e2b.png)
![image](https://user-images.githubusercontent.com/4995476/146315480-ff00cb18-0776-441a-af70-c4721179266e.png)

**Comment by yedf2** [comment]
已修复
